"""Generate the two Task-6 RL arm configs from configs/_rl_scoring.frag.

Both arms (TL-A' and TL-C) run the IDENTICAL objective (spec section 5.1) with
inception removed (spec section 4.1). They differ ONLY in `agent_file` and the
output paths that name the arm. Everything else - scoring components and their
transforms, learning_strategy, batch_size, max_steps, diversity_filter, seed,
batch ordering - is generated from the same template so the two files cannot
drift apart by hand-editing one of them.

Unlike scripts/make_scoring_config.py (section 7, `run_type = "scoring"`, which
strips the `stage.` prefix), configs/_rl_scoring.frag already carries the
`[[stage.scoring.component]]` headers a `staged_learning` RL config needs, so
it is inlined verbatim - no header rewrite here.
"""

from __future__ import annotations

import argparse
import sys

FRAG = "configs/_rl_scoring.frag"

ARMS = {
    "A-prime": {
        "tag": "v2_TL-A-prime",
        "agent_file": "priors/focused_A_prime.prior",
    },
    "C": {
        "tag": "v2_TL-C",
        "agent_file": "REINVENT4/priors/reinvent.prior",
    },
}


def build_config(arm: str, frag_path: str = FRAG) -> str:
    if arm not in ARMS:
        raise ValueError(f"unknown arm {arm!r}; choose one of {sorted(ARMS)}")
    tag = ARMS[arm]["tag"]
    agent_file = ARMS[arm]["agent_file"]

    with open(frag_path) as handle:
        scoring = handle.read()

    preamble = "\n".join([
        f"# GENERATED by scripts/make_rl_config.py --arm {arm} - do not edit by hand.",
        f"# Scoring components come from {frag_path} (spec section 5.1), verbatim.",
        "# Inception is deliberately absent - spec section 4.1: inception.py truncates",
        "# by score and never re-admits an evicted seed, and its loss uses the PRIOR",
        "# log-likelihood, which would push the two arms in opposite directions and",
        "# contaminate the one comparison this task exists to make.",
        "#",
        f"# Arm {arm}: differs from the other arm ONLY in `agent_file` below and the",
        "# output paths that name this arm. Scoring, learning_strategy, batch_size,",
        "# max_steps, diversity_filter, and batch ordering are identical across arms.",
        'run_type = "staged_learning"',
        'device = "cuda:0"',
        f'tb_logdir = "logs/{tag}/tb"',
        "",
        "[parameters]",
        f'agent_file = "{agent_file}"',
        'prior_file = "REINVENT4/priors/reinvent.prior"',
        "batch_size = 128",
        "unique_sequences = true",
        "randomize_smiles = true",
        f'summary_csv_prefix = "results/{tag}/rl"',
        "",
        "[learning_strategy]",
        'type = "dap"',
        "sigma = 128",
        "rate = 0.0001",
        "",
        "[[stage]]",
        "max_steps = 1000",
        'termination = "simple"',
        "max_score = 1.0",
        f'chkpt_file = "results/{tag}/rl_final.chkpt"',
        "",
        "[stage.diversity_filter]",
        'type = "IdenticalMurckoScaffold"',
        "bucket_size = 25",
        "minscore = 0.4",
        "",
        "[stage.scoring]",
        'type = "geometric_mean"',
        "",
    ])
    return preamble + scoring


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--arm", required=True, choices=sorted(ARMS))
    parser.add_argument("--out", required=True)
    args = parser.parse_args(argv)

    text = build_config(args.arm)
    with open(args.out, "w") as handle:
        handle.write(text)
    print(f"wrote {args.out} ({len(text.splitlines())} lines)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
