"""Generate the section 7 scoring config from the files the RL run actually used.

Section 7 requires the **identical** scoring function from section 5.1. Hand-copying
it is how that requirement gets quietly broken: section 5.4 records three files
disagreeing on `SlogP` (this blueprint's "penalize above ~3",
reinvent4_avb1_scoring_config_sketch.toml's `double_sigmoid(1, 4)`, and the
actually-run new3.toml's `reverse_sigmoid(2, 5, 0.4)`). So nothing here is retyped.

Two sources, because the objective lives in two places:
  configs/_rl_scoring.frag                      the four components
  reinvent4_avb1_scoring_config_sketch.toml     the [stage.scoring] aggregator

A staged_learning run nests its scoring under `[[stage]]`; a `run_type = "scoring"`
run does not. The only transformation applied is dropping that `stage.` prefix from
table headers, so tests/test_scoring_config.py can assert the emitted component tree
is byte-for-byte the frag's parsed tree.
"""

from __future__ import annotations

import argparse
import re
import sys
import tomllib

__all__ = ["FRAG", "SKETCH", "aggregator_type", "build_config", "strip_stage_prefix"]

FRAG = "configs/_rl_scoring.frag"
SKETCH = "reinvent4_avb1_scoring_config_sketch.toml"
DEFAULT_OUTPUT = "configs/score_panel.toml"

# Only a TOML table header can be rewritten. A comment or a value may contain
# "[stage.scoring]" or a bracketed SMARTS, and both must survive verbatim.
_HEADER = re.compile(r"^(\[{1,2})stage\.scoring\.", re.MULTILINE)


def strip_stage_prefix(text: str) -> str:
    """Rewrite `[[stage.scoring.component]]` to `[[scoring.component]]`."""
    return _HEADER.sub(r"\1scoring.", text)


def aggregator_type(sketch_path: str = SKETCH) -> str:
    """The aggregator the RL stage declared, read rather than assumed.

    `[[stage]]` is an array of tables, so this asserts there is exactly one stage
    before reading it. The section 5 redesign deleted the 200-step focus stage
    precisely so there would be one; if a second is ever added, silently scoring
    the panel against stage 0's objective would be wrong, and this raises instead.
    """
    with open(sketch_path, "rb") as handle:
        stages = tomllib.load(handle)["stage"]
    if len(stages) != 1:
        raise ValueError(
            f"{sketch_path} declares {len(stages)} stages; section 7 needs the "
            "single-stage objective (blueprint section 5.2) - say which stage to use"
        )
    return stages[0]["scoring"]["type"]


def build_config(smiles_file: str, output_csv: str,
                 frag_path: str = FRAG, sketch_path: str = SKETCH) -> str:
    """The full scoring config text: preamble, aggregator, then the frag verbatim."""
    with open(frag_path) as handle:
        components = strip_stage_prefix(handle.read())
    preamble = "\n".join([
        "# GENERATED by scripts/make_scoring_config.py - do not edit by hand.",
        f"# Components come from {frag_path}, the aggregator from {sketch_path};",
        "# both are the files the section 5.1 RL run used. Regenerate after any",
        "# change to either, or tests/test_scoring_config.py fails.",
        "#",
        "# PAINS is absent here and present in scripts/objective.py: CustomAlerts",
        "# takes SMARTS and the RDKit PAINS catalog is a Python object, so the two",
        "# scorers differ by exactly that one filter. No benchmark-panel molecule",
        "# matches PAINS (tests/test_scoring_config.py), so on this panel they agree.",
        'run_type = "scoring"',
        'device = "cuda:0"',
        "",
        "[parameters]",
        f'smiles_file = "{smiles_file}"',
        f'output_csv = "{output_csv}"',
        "",
        "[scoring]",
        f'type = "{aggregator_type(sketch_path)}"',
        "",
    ])
    return preamble + components


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--smiles-file", default="results/panel_curated.smi")
    parser.add_argument("--output-csv", default="results/score_panel.csv")
    parser.add_argument("--out", default=DEFAULT_OUTPUT)
    args = parser.parse_args(argv)

    text = build_config(args.smiles_file, args.output_csv)
    with open(args.out, "w") as handle:
        handle.write(text)
    print(f"wrote {args.out} ({len(text.splitlines())} lines)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
