"""Generate the arm-scoped sampling configs (Task 7).

Every arm samples from its own RL checkpoint, 20,000 molecules, into its own
arm-scoped output CSV. Arms differ ONLY in `model_file` and `output_file` -
everything else (num_smiles, unique_molecules, randomize_smiles) is identical,
generated from one template so the configs cannot drift apart by hand-editing
one of them. Same precedent as scripts/make_rl_config.py for the RL configs.

THE PATH PREFIX IS PART OF THE ARM, not a format string. It used to be spelled
`results/v2_{arm}` in this docstring and hardcoded per entry below, which is why
v4's arm could not be expressed here at all: TL-B's checkpoint is under
results/v4_TL-B. Keeping the full path in each entry is what lets two campaigns
coexist, and it matches make_rl_config.ARMS, where `tag` carries the same
information.
"""

from __future__ import annotations

import argparse
import sys

ARMS = {
    "TL-A-prime": {
        "model_file": "results/v2_TL-A-prime/rl_final.chkpt",
        "output_file": "results/v2_TL-A-prime/sample.csv",
    },
    "TL-B": {
        "model_file": "results/v4_TL-B/rl_final.chkpt",
        "output_file": "results/v4_TL-B/sample.csv",
    },
    "TL-C": {
        "model_file": "results/v2_TL-C/rl_final.chkpt",
        "output_file": "results/v2_TL-C/sample.csv",
    },
}


def build_config(arm: str) -> str:
    if arm not in ARMS:
        raise ValueError(f"unknown arm {arm!r}; choose one of {sorted(ARMS)}")
    cfg = ARMS[arm]

    return "\n".join([
        f"# GENERATED by scripts/make_sample_config.py --arm {arm} - do not edit by hand.",
        f"# Blueprint section 6, arm {arm}: sample from the Task-6 RL checkpoint for",
        "# this arm. num_smiles is the low end of section 6's 20,000-50,000 range.",
        'run_type = "sampling"',
        'device = "cuda:0"',
        "",
        "[parameters]",
        f'model_file = "{cfg["model_file"]}"',
        f'output_file = "{cfg["output_file"]}"',
        "num_smiles = 20000",
        "unique_molecules = true",
        "randomize_smiles = true",
        "",
    ])


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--arm", required=True, choices=sorted(ARMS))
    parser.add_argument("--out", required=True)
    args = parser.parse_args(argv)

    text = build_config(args.arm)
    with open(args.out, "w") as handle:
        handle.write(text)
    print(f"wrote {args.out} ({len(text.splitlines())} lines)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
