"""Meeko PDBQT for an isoform receptor, from prepare_isoform's manifest (spec §10.3).

The alphaVbeta1 receptor was prepared by scripts/prepare_receptor_pdbqt.py,
whose binding-site list and anchor atoms are 8W30's own. Section 10 docks the
same ligands against alphaVbeta3 (6MK0) and alphaVbeta6 (9CZD), whose sites
are different residues and whose MIDAS ions are Mn and Mg. This driver reuses
that module's reusable parts -- the truncation of incomplete residues and the
Meeko command -- and takes everything structure-specific from the manifest
prepare_isoform.py wrote.

WHAT IS AND IS NOT CHECKED. The MIDAS ion must survive the conversion: losing
it deletes the interaction the whole campaign is about, and `obabel -p 7.4`
once removed all six calciums from the alphaVbeta1 receptor while the scores
still looked normal. Partial charges are NOT checked here. They mattered when
the engine was AutoDock-GPU, whose AD4 scoring has an electrostatic term; the
redocking gate rejected that engine and Uni-Dock's Vina scoring has no charge
term at all, so a zero-charge metal changes nothing for this campaign.

The box comes from the isoform's OWN crystal ligand, through the same
dock_unidock.box_from_ligand the production run uses. Section 10.1 compares
the SAME ligand's score across receptors and takes the difference, so a box
built by a different rule on one receptor would put a systematic offset into
exactly the quantity that is supposed to cancel.

THE LIGAND INDEX IS WRITTEN HERE, ON THE MACHINE THAT WILL DOCK. Uni-Dock's
--ligand_index holds absolute paths, so an index generated on one machine and
committed is a file of paths that do not exist on the other. That is exactly
what happened: Uni-Dock computed the grid, reported "Total ligands: 1", and
died with `terminate called after throwing an instance of 'file_error'`. The
index is git-ignored and regenerated by this script.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

__all__ = ["StaleInputError", "binding_site_from_manifest", "metal_present",
           "prepare", "prepare_crystal_ligand", "verify_ligand_provenance"]


class StaleInputError(RuntimeError):
    """The prepared ligand was not made the way this pipeline makes ligands.

    On the cluster, prepare_isoform.py failed -- the old revision was checked
    out and did not know --ligand-ccd -- and this script and the docking then
    ran on the Open Babel ligand.sdf left over from before, reproducing the
    invalid result to three decimal places. Nothing looked wrong because
    nothing said anything.
    """


def verify_ligand_provenance(isoform_dir) -> bool:
    """Was ligand.sdf built from the manifest's template? Raises if not.

    Checked by chemistry, not by timestamps: the SDF's canonical SMILES must
    equal the template's, ignoring stereochemistry and formal charge (the
    campaign deprotonates its ligands on purpose, spec 7.4).
    """
    from rdkit import Chem

    from ligand_template import TemplateMismatchError, canonical

    base = Path(isoform_dir)
    manifest_path = base / "manifest.json"
    if not manifest_path.exists():
        raise StaleInputError(f"{manifest_path} is missing; run prepare_isoform.py")
    manifest = json.loads(manifest_path.read_text())

    template = manifest.get("ligand_template")
    if not template:
        raise StaleInputError(
            f"{manifest_path} records no ligand_template. It was written by the "
            "Open Babel path, which inferred bond orders from coordinates and "
            "got both isoform ligands wrong in the alphaV-binding head. Re-run "
            "prepare_isoform.py with --ligand-ccd or --ligand-smiles.")

    sdf = base / "ligand.sdf"
    if not sdf.exists():
        raise StaleInputError(f"{sdf} is missing; run prepare_isoform.py")
    mol = next(iter(Chem.SDMolSupplier(str(sdf), removeHs=False)), None)
    if mol is None:
        raise StaleInputError(f"{sdf}: RDKit could not read a molecule")

    try:
        got, want = canonical(Chem.MolToSmiles(mol)), canonical(template)
    except TemplateMismatchError as exc:
        raise StaleInputError(f"{sdf}: {exc}")
    if got != want:
        raise StaleInputError(
            f"{sdf} does not match the manifest's template -- it is left over "
            f"from an earlier preparation:\n    ligand.sdf {got}\n"
            f"    template   {want}\nRe-run prepare_isoform.py.")
    return True


def binding_site_from_manifest(manifest: dict) -> set:
    """(chain, resseq) pairs the truncation step must never alanine.

    prepare_isoform derives these from the structure -- every polymer residue
    within 5 A of the crystal ligand -- rather than listing them per isoform.
    An incomplete side chain among them stops the run, because the pose gate
    measures contacts to those exact side chains.
    """
    return {(chain, int(seq))
            for chain, seq in manifest.get("binding_site_residues", [])}


def metal_present(pdbqt_path: str, metal: tuple) -> bool:
    """Is the MIDAS ion still in the converted receptor?

    `metal` is (resname, chain, resseq) as the manifest records it.
    """
    resname, chain, resseq = metal[0].upper(), metal[1], str(metal[2])
    for line in Path(pdbqt_path).read_text().splitlines():
        if not line.startswith(("ATOM", "HETATM")):
            continue
        if (line[17:20].strip().upper() == resname and line[21] == chain
                and line[22:26].strip() == resseq):
            return True
    return False


def prepare_crystal_ligand(isoform_dir: str) -> str:
    """Meeko PDBQT for the isoform's own crystal ligand, plus its index.

    Section 10.3 redocks this ligand into this receptor. Hydrogens are added
    with addCoords so the heavy atoms do not move: the RMSD criterion
    compares the redocked pose against exactly these coordinates, and
    re-embedding would change what is being reproduced.
    """
    from rdkit import Chem

    from ligands_to_pdbqt import prepare_one

    base = Path(isoform_dir)
    mol = Chem.MolFromMolFile(str(base / "ligand.sdf"), removeHs=False)
    if mol is None:
        raise ValueError(f"{base}/ligand.sdf: RDKit could not read it")
    mol = Chem.AddHs(mol, addCoords=True)
    mol.SetProp("_Name", f"XTAL_{base.name}")
    text = prepare_one(mol)
    if text is None:
        raise ValueError(f"{base}/ligand.sdf: Meeko refused the ligand")

    pdbqt = base / f"XTAL_{base.name}.pdbqt"
    pdbqt.write_text(text)
    # Absolute, and written on the machine that will dock: Uni-Dock resolves
    # these paths itself and a committed index names another machine's disk.
    (base / "ligand_index.txt").write_text(str(pdbqt.resolve()) + "\n")
    return str(pdbqt)


def prepare(isoform_dir: str, box_radius: float = 8.0) -> dict:
    """Truncate, convert with Meeko, and verify. Returns a report dict."""
    from dock_unidock import box_from_ligand
    from prepare_receptor_pdbqt import (build_meeko_command, run_meeko,
                                        truncate_incomplete_residues)

    verify_ligand_provenance(isoform_dir)

    base = Path(isoform_dir)
    manifest = json.loads((base / "manifest.json").read_text())
    receptor_pdb = base / "receptor.pdb"
    ligand_sdf = base / "ligand.sdf"

    lines = receptor_pdb.read_text().splitlines()
    truncated, truncations = truncate_incomplete_residues(
        lines, binding_site=binding_site_from_manifest(manifest))
    truncated_pdb = base / "receptor_truncated.pdb"
    truncated_pdb.write_text("\n".join(truncated + ["END"]) + "\n")

    box = box_from_ligand(str(ligand_sdf))
    basename = str(base / "receptor")
    run_meeko(build_meeko_command(str(truncated_pdb), basename, box,
                                  box_radius=box_radius))

    pdbqt = f"{basename}.pdbqt"
    if not Path(pdbqt).exists():
        raise FileNotFoundError(f"Meeko produced no {pdbqt}")

    ligand_pdbqt = prepare_crystal_ligand(isoform_dir)

    metal = manifest["midas_metal"]
    return {
        "ligand_pdbqt": ligand_pdbqt,
        "ligand_index": str(base / "ligand_index.txt"),
        "isoform_dir": str(base),
        "pdbqt": pdbqt,
        "box": box,
        "truncated_residues": len(truncations),
        "binding_site_residues": len(binding_site_from_manifest(manifest)),
        "midas_metal": metal,
        "midas_present": metal_present(pdbqt, metal),
    }


def main(argv=None) -> int:
    p = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    p.add_argument("--isoform-dir", required=True,
                    help="Directory prepare_isoform.py wrote (receptor.pdb, "
                         "ligand.sdf, manifest.json).")
    p.add_argument("--box-radius", type=float, default=8.0,
                    help="Meeko --delete_bad_res_from_box_radius.")
    args = p.parse_args(argv)

    try:
        report = prepare(args.isoform_dir, args.box_radius)
    except StaleInputError as exc:
        sys.stderr.write(f"{exc}\n")
        return 2
    print(f"{report['isoform_dir']}")
    print(f"  box center  ({report['box']['center_x']:.3f}, "
          f"{report['box']['center_y']:.3f}, {report['box']['center_z']:.3f})")
    print(f"  box size    ({report['box']['size_x']:.3f}, "
          f"{report['box']['size_y']:.3f}, {report['box']['size_z']:.3f})")
    print(f"  truncated   {report['truncated_residues']} incomplete residues "
          f"(none of the {report['binding_site_residues']} binding-site ones)")
    print(f"  MIDAS {report['midas_metal']}  present in PDBQT: "
          f"{report['midas_present']}")
    print(f"  -> {report['pdbqt']}")
    print(f"  -> {report['ligand_pdbqt']}")
    print(f"  -> {report['ligand_index']}  (absolute paths, this machine)")

    if not report["midas_present"]:
        sys.stderr.write(
            "the MIDAS ion did not survive the conversion. Docking against "
            "this receptor would search a site with no metal, and every pose "
            "would fail the coordination criterion for a reason that is not "
            "chemical.\n")
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
